/**:
  ros__parameters:
    vehicle:
      type: diagnostic_aggregator/AnalyzerGroup
      path: vehicle
      analyzers:
        vehicle_errors:
          type: diagnostic_aggregator/GenericAnalyzer
          path: vehicle_errors
          contains: [": vehicle_errors"]
          timeout: 1.0
        node_alive_monitoring:
          type: diagnostic_aggregator/AnalyzerGroup
          path: node_alive_monitoring
          analyzers:
            # TODO(Tier IV): Consider splitting sensor input and control command output
            topic_status:
              type: diagnostic_aggregator/GenericAnalyzer
              path: topic_status
              contains: [": vehicle_topic_status"]
              timeout: 1.0
        calibration:
          type: diagnostic_aggregator/AnalyzerGroup
          path: calibration
          analyzers:
            accel_brake_map_calibrator:
              type: diagnostic_aggregator/GenericAnalyzer
              path: accel_brake_map_calibrator
              contains: [": accel_brake_map_calibrator"]
              timeout: 1.0
